Repository camptocamp/demo_geomapfish, pull requests merged in 2022-05, with the labels that each got.

#403 Add pytreeLidarprofileJsonUrl for desktop interface
  geoportal/vars.yaml
Labels: backport-prod-2-8, backport-prod-2-7-advance, backport-prod-2-8-advance

#437 Add pytreeLidarprofileJsonUrl for desktop interface (extended on desk…
  geoportal/vars.yaml
Labels: backport-prod-2-8, backport-prod-2-8-advance

#427 Check the docker compose version
  .github/workflows/test.yaml
  Makefile
  ci/docker-compose-check
  docker-compose-db.yaml
  tests/__init__.py
  tests/test_app.py
Labels: backport prod-2-8, backport prod-2-7-advance, backport prod-2-8-advance

#445 Fix advance add missing OSM database environment variables
  docker-compose.yaml
Labels: backport prod-2-8-advance

#455 Configure Renovate
  .editorconfig
  .github/dependabot.yaml
  .github/renovate.json5
  .github/workflows/dependabot-auto-merge.yaml
Labels: backport prod-2-8-advance

#472 Switch to Poetry
  .github/workflows/main.yaml
  .github/workflows/test.yaml
  Makefile
  custom/Dockerfile
  custom/Pipfile
  custom/Pipfile.lock
  custom/poetry.lock
  custom/pyproject.toml
  custom/requirements.txt
Labels: backport prod-2-8, backport prod-2-7-advance, backport prod-2-8-advance

#490 Also ignore files with version
  ci/cleanup
Labels: backport prod-2-8-advance
