Repository camptocamp/demo_geomapfish, pull requests merged in 2023-03, with the labels that each got.

#887 Updated extent and added layers for Bavaria
  geoportal/vars.yaml
  qgisserver/bavaria_leisure_themes.qgs
Labels: backport prod-2-8

#892 Change the position where we go with the button
  geoportal/geomapfish_geoportal/static/apihelp/index.html.tmpl
Labels: backport prod-2-7, backport prod-2-7-advance, backport prod-2-8-advance

#897 Set a background color of the OSM base layer
  mapserver/osm-basemap.map.tmpl
Labels: backport prod-2-8-advance

#917 Use OGC server named QGIS server in the WFS permalink
  geoportal/vars.yaml
Labels: backport prod-2-8-advance
